version: '3.9'

services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - '3306:3306'
        volumes:
            - db_data:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    php:
        build: .
        # image: php:8.2-apache
        volumes:
            - ./dist:/var/www/html
        ports:
            - '8080:80'
        depends_on:
            - db

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: admin
            PMA_PASSWORD: admin
        ports:
            - '8081:80'
        depends_on:
            - db

volumes:
    db_data:
