import type { BlogEntry } from './types';

const blog: BlogEntry = {
	id: "31",
	numericId: 31,
	slug: "self-hosting-services",
	title: "Self-Hosting Unlocked 🚀",
	description: "Self-hosting services has been a passion of mine for a while now. Recently, I took that passion a step further by building a custom Raspberry Pi cluster, utilizing orchestration tools to manage and distribute services across it. But why go down the rabbit hole of self-hosting? In this blog post, I discuss the various self-hosted services I have built and how they can provide value to others.",
	date: "2025-12-04",
	link: "https://vonkprogramming.nl/blogs/self-hosting-services",
	content: `
Self-hosting services has been a passion of mine for a while now.
  Recently, I took that passion a step further by building a custom
  Raspberry Pi cluster, utilizing orchestration tools to manage and
  distribute services across it. But why go down the rabbit hole of
  self-hosting?

  For anyone running a website or digital business, services like
  monitoring, tracking, backups, and automation are very valuable. While
  there are many enterprise providers offering these tools, they often
  come with bloated feature sets, high costs, and privacy concerns.
  Sometimes, you don't need a complex enterprise suite; you just
  need a reliable service that tells you if your SSL certificate has
  expired or if your site is down.

  What started as a fun technical challenge has evolved into something
  more. I realized that the robust, lightweight solutions I built for
  myself could provide value to others. So if you want someone to spar
  with or help you set up self-hosted services for your business,
  VonkProgramming is here to help and if you do not want to manage it
  yourself, I can host it for you.

## Provided Services

  Here is a breakdown of the self-hosted services I am currently
  running, which I can help you with to streamline your business:

## 1. Uptime Monitoring & Alerts

  I host a straightforward, reliable monitoring service that performs
  health checks on specific pages at defined intervals. It goes beyond
  simple "is it up?" checks, allowing for custom validation
  logic.

- The Benefit: If a check fails, whether it’s a downtime event or an SSL expiration, the system immediately notifies you via email or Telegram. This ensures that I (and now you) are the first to know about any issues, rather than waiting for a client to complain.

[Image: Uptime Kuma monitoring dashboard]

  Uptime Kuma monitoring dashboard

## 2. Privacy-First Analytics

  Many modern analytics tools are overly intrusive, expensive, and
  cluttered. I created a custom tracking tool designed to respect user
  privacy while still providing actionable data. This data will be sent
  as a report generated by AI to you every week with a data export of
  that week.

- The Benefit: This tool tracks usage anonymously, meaning there is no IP storage and no personal data harvesting. Futhermore it sends you a weekly report with specific advice to reduce time spent analysing the tracking data.

[Image: Matomo analytics dashboard]

  Example of a weekly AI-generated tracking report

## 3. Workflow Automation

  While I write code for complex logic, some tasks are simply handled
  better by automation software. I host a dedicated workflow automation
  platform that streamlines routine business processes.

- The Benefit: This allows for the rapid creation of automated tasks, such as updating subscriber lists automatically whenever a new blog post is published, without the need for custom development hours.

[Image: n8n workflow automation dashboard]

  n8n workflow automation dashboard

## 4. Git Backup & Redundancy

  I once read a story about a developer who lost access to their GitHub
  account due to a policy misunderstanding, losing years of hard work.
  While platforms like GitHub are excellent, redundancy is a cornerstone
  of professional software management.

- The Benefit: My self-hosted Git backup service mirrors repositories automatically. This ensures business continuity and protects intellectual property in the rare event of a platform outage or account access issue.

[Image: Gitea backup dashboard showing repository backups]

  Gitea is an easily self-hosted Version Control platform

## Personal services

## 1. AI Business Intelligence Agent

  I am running a secure, self-hosted AI agent with restricted access to
  my data sources. This allows me to "talk" to my data.

- The Benefit: Instead of digging through logs or spreadsheets, I can simply ask my agent, "Was any service down today?" and receive a concise, AI-generated summary. Note: While my personal agent is specific to my data, I can build custom AI agents for clients tailored to their specific data needs upon request.

## 2. Container Orchestration

  To manage all of the above, I utilize a Docker Swarm environment
  running on my cluster.

- The Benefit: This provides a visual overview of service health, status, and resource usage, ensuring that the infrastructure remains stable and scalable.

[Image: Portainer dashboard showing container orchestration]

  Portainer dashboard showing container orchestration

## Why self-hosted services?

  These services provide simple, low-cost, and low-maintenance solutions
  ideal for Small-to-Medium Enterprises (SMEs), solo developers, or
  side-project owners.

  Additionally, this approach allows you to consolidate these needs.
  Instead of juggling multiple subscriptions and logins for separate
  monitoring, analytics, and backup services, you can get everything you
  need from a single, reliable provider, which can either be yourself or
  VonkProgramming.

  Need Something Custom? If you require a service beyond what is listed
  above, we are ready to build it. We are happy to collaborate with you
  to design, develop, and potentially host custom solutions tailored
  specifically to your unique requirements.

  Interested in elevating your business? All of these services are
  available for use upon inquiry. Whether you need a simple monitoring
  setup or a full suite of self-hosted tools, get in touch with me at
  VonkProgramming. Let’s discuss how we can build a resilient, private,
  and efficient foundation for your business.

 (window.location.href = "/contact")}
  class="block mt-4 bg-blue-600 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-400 text-white font-semibold py-3 px-6 rounded-lg shadow-lg transition-colors mx-auto w-fit cursor-pointer"
>
  Contact to get started
`,
};

export default blog;
