name: vonkprogramming-pipeline
on:
  push:
    branches:
      - master

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 💻 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: 💻 Install npm dependencies
        run: npm ci
      - name: 📦 Pack node_modules
        run: tar -czf node_modules.tar.gz node_modules
      - name: 📦 Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules.tar.gz
          retention-days: 1

  quality:
    name: Quality checks
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 💻 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: 📦 Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
      - name: 📦 Unpack node_modules
        run: tar -xzf node_modules.tar.gz
      - name: 🔍 Lint
        run: npm run lint
      - name: 🗒️ Vulnerability scan
        run: npm audit

  build:
    name: Build
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 💻 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: 📦 Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
      - name: 📦 Unpack node_modules
        run: tar -xzf node_modules.tar.gz
      - name: 🗺️ Generate Sitemap
        run: npm run generate-sitemap
      - name: 📄 Generate Static Content
        run: npm run generate-static-content
      - name: 🔨 Build
        run: npm run build --production
      - name: 📦 Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          include-hidden-files: true
          retention-days: 1

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: 📝 Create config.php file
        run: |
          echo "<?php" > ./dist/scripts/config.php
          echo "\$DB_SERVER='${{ secrets.DB_SERVER }}';" >> ./dist/scripts/config.php
          echo "\$DB_NAME='${{ secrets.DB_NAME }}';" >> ./dist/scripts/config.php
          echo "\$DB_USERNAME='${{ secrets.DB_USERNAME }}';" >> ./dist/scripts/config.php
          echo "\$DB_PASSWORD='${{ secrets.DB_PASSWORD }}';" >> ./dist/scripts/config.php
          echo "\$ACCESS_TOKEN='${{ secrets.ACCESS_TOKEN }}';" >> ./dist/scripts/config.php
      - name: 📁 Publish
        uses: Creepios/sftp-action@v1.0.5
        with:
          host: "ssh.strato.com"
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: "./dist"
          remotePath: "./site"
